export interface Post {
  id: string;
  title: string;
  subtitle: string;
  date: string;
  readMin: number;
  tags: string[];
  category: string;
  excerpt: string;
  body: Block[];
}

interface Block {
  type: 'p' | 'h2' | 'code' | 'quote';
  text?: string;
  lang?: string;
}

export const POSTS: Post[] = [
  {
    id: "nextjs-14-migration-lessons",
    title: "Next.js 14로 마이그레이션하며 배운 5가지",
    subtitle: "App Router, Server Components, 그리고 내가 틀렸던 것들",
    date: "2026-06-16",
    readMin: 7,
    tags: ["Next.js", "블로그"],
    category: "Frontend",
    excerpt: "Pages Router에서 App Router로 갈아탈 때 '그냥 폴더 이름만 바꾸면 되지 않나?' 라고 생각했다. 완전히 틀렸다.",
    body: [
      { type: "p", text: "이 블로그를 Next.js 14 App Router로 직접 만들면서 배운 것들을 정리했다. 튜토리얼에선 안 가르쳐주는, 실제로 부딪혀야 아는 것들이다." },
      { type: "h2", text: "1. 'use client'는 예외가 아니라 경계다" },
      { type: "p", text: "처음엔 useState를 쓰는 컴포넌트마다 습관적으로 'use client'를 붙였다. 그런데 그건 Server Component의 이점을 전부 날리는 짓이다. 'use client'는 '이 컴포넌트부터 아래는 클라이언트에서만 돌아간다'는 경계 선언이다. 가능한 한 트리의 말단에 두어야 한다." },
      { type: "code", lang: "typescript", text: "// 나쁜 예: 부모 전체를 클라이언트로 만든다\n'use client'\nexport default function PostPage({ post }) {\n  const [liked, setLiked] = useState(false)\n  return (\n    <article>\n      <PostBody post={post} />  {/* 서버에서 렌더할 수 있었는데 */}\n      <LikeButton liked={liked} onClick={() => setLiked(true)} />\n    </article>\n  )\n}\n\n// 좋은 예: 인터랙션이 필요한 부분만 분리\n// app/posts/[id]/page.tsx (Server Component)\nexport default function PostPage({ post }) {\n  return (\n    <article>\n      <PostBody post={post} />  {/* 서버 렌더링 */}\n      <LikeButton />            {/* 얘만 'use client' */}\n    </article>\n  )\n}" },
      { type: "h2", text: "2. fetch 캐싱은 기본이 aggressive하다" },
      { type: "p", text: "App Router에서 fetch는 기본적으로 결과를 캐시한다. 개발 중엔 데이터가 안 바뀌는 것 같아서 한참 헤맸다. 동적 데이터를 쓸 땐 cache: 'no-store'를 명시하거나, next: { revalidate: 60 }으로 주기를 지정해야 한다." },
      { type: "code", lang: "typescript", text: "// 정적 (빌드 시 1회)\nconst data = await fetch('/api/posts')\n\n// 60초마다 재검증\nconst data = await fetch('/api/posts', { next: { revalidate: 60 } })\n\n// 항상 최신\nconst data = await fetch('/api/posts', { cache: 'no-store' })" },
      { type: "h2", text: "3. layout.tsx와 page.tsx의 역할을 명확히 구분하라" },
      { type: "p", text: "layout.tsx는 공유 UI다. 같은 경로 아래에서 페이지가 바뀌어도 layout은 다시 렌더링되지 않는다. 그래서 nav, sidebar, 인증 상태 같은 것들은 layout에 넣어야 한다. page.tsx는 그 경로의 고유 콘텐츠만." },
      { type: "h2", text: "4. 서버 에러는 error.tsx가, 로딩은 loading.tsx가 잡는다" },
      { type: "p", text: "각 폴더에 error.tsx와 loading.tsx를 두면 자동으로 Error Boundary와 Suspense가 연결된다. 따로 설정할 필요 없다. 처음엔 이게 어디서 작동하는지 몰라서 Suspense를 직접 wrap하고 있었는데, 파일만 만들면 된다." },
      { type: "h2", text: "5. metadata는 export하는 방식이 두 가지다" },
      { type: "p", text: "정적 페이지는 metadata 객체를, 동적 페이지는 generateMetadata 함수를 export한다. SEO 작업할 때 혼동하기 쉬운 부분이다." },
      { type: "code", lang: "typescript", text: "// 정적 메타데이터\nexport const metadata = {\n  title: '포스트 제목',\n  description: '설명'\n}\n\n// 동적 메타데이터 (params에서 데이터 가져올 때)\nexport async function generateMetadata({ params }) {\n  const post = await getPost(params.id)\n  return { title: post.title }\n}" },
      { type: "quote", text: "App Router는 새 문법이 아니라 새 사고방식이다. '어디서 실행되나'를 항상 생각하면 나머지는 자연스럽게 따라온다." },
    ]
  },
  {
    id: "claude-code-six-months",
    title: "Claude Code로 6개월, 이제 AI 없이 못 산다",
    subtitle: "솔직한 후기: 생산성이 오른 것과 독이 된 것",
    date: "2026-06-16",
    readMin: 6,
    tags: ["Claude Code", "AI", "개발 팁"],
    category: "Technology",
    excerpt: "AI 코딩 도구가 처음 나왔을 때 '결국 시니어가 더 잘 써먹겠지'라고 생각했다. 반은 맞고 반은 틀렸다. 초보일수록 더 조심해야 하지만, 제대로 쓰면 레벨업이 빠르다.",
    body: [
      { type: "p", text: "6개월 전, Claude Code를 처음 켜고 'React 컴포넌트 하나 만들어줘'라고 했다. 동작하는 코드가 나왔고 나는 복붙했다. 그리고 3일 후 버그를 잡지 못해서 처음부터 다시 짰다." },
      { type: "p", text: "이제는 다르게 쓴다. 그 차이를 정리한다." },
      { type: "h2", text: "제대로 쓰는 법: 코드 생성기가 아니라 페어 프로그래머" },
      { type: "p", text: "가장 크게 달라진 건 요청 방식이다. '이거 만들어줘' 대신 '이 코드에서 왜 무한 렌더링이 발생하는지 설명해줘'처럼 이해를 먼저 요청한다. 코드를 받기 전에 왜 그렇게 짜는지 물어본다." },
      { type: "code", lang: "typescript", text: "// 나쁜 요청: 복붙만 하게 된다\n\"useEffect로 API 호출하는 컴포넌트 만들어줘\"\n\n// 좋은 요청: 이해를 강제한다\n\"아래 useEffect에서 의존성 배열을 빈 배열로 두면\n왜 stale closure 문제가 생기는지 설명하고,\n어떻게 고치면 좋을지 알려줘\"\n\nuseEffect(() => {\n  fetchData(userId)  // userId가 바뀌어도 재실행 안 됨\n}, [])" },
      { type: "h2", text: "가장 효과적이었던 사용 패턴 3가지" },
      { type: "p", text: "첫째, 에러 메시지 디버깅. 스택 트레이스 전체를 붙여넣고 '이 에러의 원인과 해결 방법을 알려줘'라고 하면 구글링 10분을 2분으로 줄여준다." },
      { type: "p", text: "둘째, 코드 리뷰 요청. PR 올리기 전에 '이 코드에서 놓친 엣지 케이스나 성능 문제가 있으면 알려줘'라고 한다. 시니어 리뷰어 같은 역할을 한다." },
      { type: "p", text: "셋째, 개념 설명 + 예시 요청. 공식 문서가 이해 안 될 때, '이걸 실생활 비유로 설명하고 내 코드에 적용하면 어떻게 되는지 보여줘'라고 하면 훨씬 빠르게 이해된다." },
      { type: "h2", text: "조심해야 할 것" },
      { type: "p", text: "가장 큰 함정은 AI가 자신 있게 틀린다는 것이다. 특히 최신 라이브러리 버전이나 특정 환경 설정에서 존재하지 않는 API를 만들어내기도 한다. 생성된 코드는 반드시 동작을 이해하고 나서 사용해야 한다." },
      { type: "quote", text: "AI는 생각을 대신해주는 도구가 아니라, 생각의 속도를 높여주는 도구다. 생각 자체를 넘기면 결국 코드의 주인이 사라진다." },
    ]
  },
  {
    id: "react-hooks-game-patterns",
    title: "게임을 만들며 배운 React Hooks 정리",
    subtitle: "useRef, useCallback, useEffect — 헷갈리는 이유와 해결법",
    date: "2026-06-16",
    readMin: 8,
    tags: ["React", "JavaScript", "Hooks"],
    category: "Frontend",
    excerpt: "스네이크 게임을 React로 만들다가 useRef와 useState의 차이를 처음으로 진짜 이해했다. 게임은 훅의 특성을 날카롭게 드러내는 최고의 예제다.",
    body: [
      { type: "p", text: "처음 React Hooks를 배울 때 가장 헷갈렸던 건 'useRef vs useState'였다. 둘 다 값을 저장하는데, 언제 어떤 걸 쓰나?" },
      { type: "p", text: "스네이크 게임을 만들면서 답을 찾았다. 게임 개발은 상태 관리의 경계가 명확해서 훅의 차이를 체감하기 좋다." },
      { type: "h2", text: "useRef — '렌더링과 무관한 값'을 담는 박스" },
      { type: "p", text: "스네이크 게임엔 setInterval이 필요하다. 그런데 인터벌 ID를 useState에 저장하면 저장할 때마다 리렌더링이 일어난다. 렌더링이 필요 없는 값이라면 useRef를 써야 한다." },
      { type: "code", lang: "typescript", text: "// 나쁜 예: 인터벌 ID를 state로 관리하면 불필요한 리렌더링 발생\nconst [intervalId, setIntervalId] = useState<number | null>(null)\n\n// 좋은 예: 렌더링에 영향 없는 값은 ref\nconst intervalRef = useRef<number | null>(null)\n\nfunction startGame() {\n  intervalRef.current = setInterval(moveSnake, 150)\n}\n\nfunction stopGame() {\n  if (intervalRef.current) clearInterval(intervalRef.current)\n}" },
      { type: "h2", text: "useCallback — 함수를 '기억'시키는 이유" },
      { type: "p", text: "게임 키 입력 핸들러를 useEffect 안에서 addEventListener로 등록했다. 그런데 컴포넌트가 리렌더링될 때마다 핸들러 함수가 새로 만들어지고, 이벤트 리스너가 계속 추가됐다." },
      { type: "code", lang: "typescript", text: "// 문제: 매 렌더마다 새 함수 → 이벤트 리스너 누적\nuseEffect(() => {\n  const handleKey = (e: KeyboardEvent) => setDirection(e.key)\n  window.addEventListener('keydown', handleKey)\n  return () => window.removeEventListener('keydown', handleKey)\n}, [])  // handleKey가 클로저 밖에 있어서 stale\n\n// 해결: useCallback으로 함수 메모이제이션\nconst handleKey = useCallback((e: KeyboardEvent) => {\n  setDirection(e.key)\n}, [])  // 의존성이 없으니 처음 한 번만 생성\n\nuseEffect(() => {\n  window.addEventListener('keydown', handleKey)\n  return () => window.removeEventListener('keydown', handleKey)\n}, [handleKey])  // handleKey가 바뀌면 재등록" },
      { type: "h2", text: "useEffect 의존성 배열 — 진짜 의미" },
      { type: "p", text: "의존성 배열은 '이 값이 바뀔 때 effect를 다시 실행해'라는 신호다. 빈 배열 []은 '처음 한 번만', 없으면 '매 렌더마다'. 게임에서 score가 바뀔 때만 최고점 저장 로직을 실행하고 싶다면:" },
      { type: "code", lang: "typescript", text: "useEffect(() => {\n  if (score > highScore) {\n    setHighScore(score)\n    localStorage.setItem('highScore', String(score))\n  }\n}, [score])  // score가 바뀔 때만 실행" },
      { type: "h2", text: "정리: 언제 무엇을 쓰나" },
      { type: "p", text: "화면에 보여야 하면 useState, 렌더링과 무관한 값 저장(인터벌 ID, DOM 참조 등)이면 useRef, 함수를 이벤트 리스너나 의존성으로 넘길 땐 useCallback, 비싼 계산 결과를 캐시하려면 useMemo." },
      { type: "quote", text: "Hooks는 각각의 '책임'이 다르다. 화면을 바꾸는 책임은 useState, 값을 유지하는 책임은 useRef. 이 기준만 기억하면 절반은 해결된다." },
    ]
  },
  {
    id: "typescript-generics-three-patterns",
    title: "TypeScript 초보자를 위한 3가지 제네릭 패턴",
    subtitle: "겁먹지 마라, 제네릭은 그냥 '나중에 채울 빈칸'이다",
    date: "2026-06-16",
    readMin: 6,
    tags: ["TypeScript", "초보자"],
    category: "Frontend",
    excerpt: "제네릭 문서를 처음 읽었을 때 `<T>`가 뭔지 몰라서 닫아버렸다. 이제는 하루에 10번 이상 쓴다. 진짜로 필요한 패턴만 3가지 골랐다.",
    body: [
      { type: "p", text: "제네릭을 한 문장으로 설명하면: '타입을 나중에 결정하는 빈칸'이다. 함수를 쓸 때 어떤 타입을 넣을지 그때그때 정할 수 있게 해준다." },
      { type: "h2", text: "패턴 1: 반환 타입을 입력 타입에 맞추기" },
      { type: "p", text: "API 응답을 파싱하는 함수를 만든다고 하자. User를 파싱할 수도 있고, Post를 파싱할 수도 있다. 제네릭 없이 짜면 any를 쓰거나 함수를 여러 개 만들어야 한다." },
      { type: "code", lang: "typescript", text: "// any를 쓰면 타입 안전성이 사라진다\nfunction parseResponse(data: any): any {\n  return JSON.parse(data)\n}\n\n// 제네릭으로 입력-출력 타입을 연결\nfunction parseResponse<T>(data: string): T {\n  return JSON.parse(data) as T\n}\n\n// 사용할 때 타입을 지정\nconst user = parseResponse<User>(apiResponse)  // user: User\nconst post = parseResponse<Post>(apiResponse)  // post: Post" },
      { type: "h2", text: "패턴 2: extends로 제네릭에 조건 걸기" },
      { type: "p", text: "모든 타입을 받는 게 아니라, id 속성이 있는 타입만 받고 싶을 때 extends를 쓴다. 이걸 'Generic Constraint(제네릭 제약)'라고 한다." },
      { type: "code", lang: "typescript", text: "// id 없는 타입도 들어올 수 있어서 위험\nfunction getById<T>(list: T[], id: string): T | undefined {\n  return list.find((item: any) => item.id === id)  // any 등장\n}\n\n// extends로 'id가 있는 타입만' 제한\nfunction getById<T extends { id: string }>(list: T[], id: string): T | undefined {\n  return list.find(item => item.id === id)  // 타입 안전\n}\n\n// id 없는 타입을 넣으면 컴파일 에러\ngetById([{ name: 'kelvin' }], '1')  // 에러: id 속성이 없음\ngetById([{ id: '1', name: 'kelvin' }], '1')  // 통과" },
      { type: "h2", text: "패턴 3: 여러 타입 파라미터 조합" },
      { type: "p", text: "함수가 두 가지 타입을 받아서 조합할 때 T, U처럼 여러 파라미터를 쓴다. 가장 흔한 예는 key-value 매핑이다." },
      { type: "code", lang: "typescript", text: "// 배열을 특정 키 기준으로 객체로 변환\nfunction groupBy<T, K extends keyof T>(\n  list: T[],\n  key: K\n): Record<string, T[]> {\n  return list.reduce((acc, item) => {\n    const groupKey = String(item[key])\n    return {\n      ...acc,\n      [groupKey]: [...(acc[groupKey] || []), item]\n    }\n  }, {} as Record<string, T[]>)\n}\n\n// 사용 예\nconst posts = [\n  { id: 1, category: 'React', title: '...' },\n  { id: 2, category: 'TypeScript', title: '...' },\n  { id: 3, category: 'React', title: '...' },\n]\n\nconst byCategory = groupBy(posts, 'category')\n// { React: [...], TypeScript: [...] }" },
      { type: "quote", text: "제네릭을 처음 볼 때 겁먹는 이유는 수학적 기호처럼 생겼기 때문이다. 그냥 '여기 타입 이름은 나중에 정할게'라는 빈칸 표시라고 생각하면 훨씬 쉽다." },
    ]
  },
  {
    id: "css-variables-dark-mode",
    title: "왜 CSS 변수로 다크모드를 만들까",
    subtitle: "--paper, --ink, --accent로 테마를 관리하는 법",
    date: "2026-06-16",
    readMin: 5,
    tags: ["CSS", "디자인"],
    category: "Frontend",
    excerpt: "다크모드를 처음 구현할 때 className을 토글하는 방식을 썼다. 동작은 했지만 유지보수가 지옥이었다. CSS 커스텀 프로퍼티가 정답인 이유를 설명한다.",
    body: [
      { type: "p", text: "이 블로그의 다크모드는 JavaScript가 한 줄도 없다. CSS 변수 두 세트와 data-theme 속성 하나로 전체 테마가 바뀐다." },
      { type: "h2", text: "className 토글 방식의 문제" },
      { type: "p", text: "흔히 쓰는 방식은 body에 dark 클래스를 붙이고 .dark .component { color: white } 식으로 짜는 것이다. 컴포넌트가 10개면 괜찮지만, 100개가 되면 CSS 파일이 두 배로 커진다. 모든 컴포넌트에 다크 버전을 따로 써야 하기 때문이다." },
      { type: "code", lang: "css", text: "/* 나쁜 예: 컴포넌트마다 다크 버전을 별도 작성 */\n.card { background: white; color: #111; }\n.dark .card { background: #1a1a1a; color: #eee; }\n\n.button { background: #0070f3; color: white; }\n.dark .button { background: #3291ff; color: white; }\n\n/* 이게 100개 컴포넌트면... */" },
      { type: "h2", text: "CSS 변수 방식: 의미 기반 토큰" },
      { type: "p", text: "컬러에 직접적인 이름(white, black) 대신 역할 이름(--paper, --ink)을 붙인다. 테마가 바뀔 때 변수 값만 교체하면 모든 컴포넌트가 자동으로 따라온다." },
      { type: "code", lang: "css", text: "/* 라이트 테마 기본값 */\n:root {\n  --paper: #fafaf8;     /* 배경 */\n  --ink: #1a1a1a;       /* 본문 텍스트 */\n  --ink-muted: #666;    /* 보조 텍스트 */\n  --accent: #2563eb;    /* 강조색 */\n  --surface: #f0f0ec;   /* 카드 배경 */\n}\n\n/* 다크 테마: 변수 값만 교체 */\n[data-theme=\"dark\"] {\n  --paper: #0f0f0f;\n  --ink: #e8e8e4;\n  --ink-muted: #999;\n  --accent: #60a5fa;\n  --surface: #1a1a1a;\n}\n\n/* 컴포넌트는 변수만 참조, 테마 무관 */\n.card {\n  background: var(--surface);\n  color: var(--ink);\n}" },
      { type: "h2", text: "JavaScript에서 테마 전환" },
      { type: "p", text: "data-theme 속성 하나만 토글하면 된다. CSS가 나머지를 알아서 처리한다." },
      { type: "code", lang: "typescript", text: "function toggleTheme() {\n  const current = document.documentElement.dataset.theme\n  document.documentElement.dataset.theme =\n    current === 'dark' ? 'light' : 'dark'\n}\n\n// localStorage에 저장해서 새로고침 후에도 유지\nfunction initTheme() {\n  const saved = localStorage.getItem('theme') || 'light'\n  document.documentElement.dataset.theme = saved\n}" },
      { type: "h2", text: "추가 이점: system preference 연동" },
      { type: "p", text: "CSS만으로도 OS 다크모드 설정을 감지할 수 있다. prefers-color-scheme 미디어 쿼리와 변수를 조합하면 JavaScript 없이 시스템 설정을 따라간다." },
      { type: "code", lang: "css", text: "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n    --paper: #0f0f0f;\n    --ink: #e8e8e4;\n    /* 나머지 다크 토큰들 */\n  }\n}" },
      { type: "quote", text: "좋은 CSS 변수 네이밍은 '무슨 색이냐'가 아니라 '무슨 역할이냐'를 표현한다. --blue-500보다 --accent가, --gray-100보다 --paper가 테마 전환에 훨씬 유연하다." },
    ]
  },
  {
    id: "react-18-concurrent",
    title: "React 18의 Concurrent Features, 6개월 써본 후기",
    subtitle: "useTransition, useDeferredValue, 그리고 Suspense의 진짜 쓸모",
    date: "2026-05-12",
    readMin: 9,
    tags: ["React", "Frontend"],
    category: "Frontend",
    excerpt: "Concurrent rendering은 마법이 아니다. 단지 React에게 '이건 좀 기다려도 돼' 라고 말할 수 있게 된 것뿐. 그게 뭘 바꾸는지 6개월간의 실전을 정리했다.",
    body: [
      { type: "p", text: "React 18이 정식 릴리즈된 지 한참 됐는데, 막상 회사 코드베이스에서 useTransition 같은 걸 본 적이 있는가? 나는 거의 없다." },
      { type: "p", text: "그런데 작년 가을, 5만 개짜리 리스트를 필터링하는 페이지에서 입력창이 끔찍하게 버벅이는 문제를 만났다." },
      { type: "h2", text: "useDeferredValue가 실제로 하는 일" },
      { type: "p", text: "공식 문서는 'UI 업데이트를 지연시킨다'고 설명하지만, 더 정확히는 두 개의 렌더 트리를 갖되 비싼 쪽이 끝나기 전까지 이전 결과를 보여준다." },
    ]
  },
  {
    id: "typescript-satisfies",
    title: "TypeScript `satisfies`가 바꾸는 작은 것들",
    subtitle: "as와 :의 사이에 새 연산자가 생겼다",
    date: "2026-04-28",
    readMin: 6,
    tags: ["TypeScript"],
    category: "Frontend",
    excerpt: "4.9에서 들어온 satisfies는 처음엔 사소해 보였다. 그런데 한 번 익숙해지면 as와 타입 어노테이션을 절반쯤 쓰지 않게 된다.",
    body: [
      { type: "p", text: "satisfies는 한 줄로 말하면, 이 값이 X 타입을 만족하는지 검사하되, 추론된 좁은 타입은 그대로 유지해줘라는 연산자다." },
    ]
  },
  {
    id: "javascript-async-promise-to-async-await",
    title: "JavaScript 비동기 처리 완벽 정리 - Promise부터 async/await까지",
    subtitle: "콜백 지옥에서 벗어나는 여정, 단계별로 이해한다",
    date: "2026-06-16",
    readMin: 7,
    tags: ["JavaScript", "비동기"],
    category: "Frontend",
    excerpt: "setTimeout 하나도 헷갈리던 시절이 있었다. 비동기가 왜 필요한지부터, Promise와 async/await의 실제 차이까지 한 번에 정리한다.",
    body: [
      { type: "p", text: "JavaScript는 싱글 스레드 언어다. 한 번에 한 가지 일만 할 수 있다. 그런데 서버에서 데이터를 받아오는 동안 화면이 얼어붙으면 안 되지 않나? 그래서 비동기가 필요하다." },
      { type: "h2", text: "왜 비동기가 필요한가" },
      { type: "p", text: "서버에 요청을 보내고 응답이 올 때까지 기다리는 건 보통 100ms~수초가 걸린다. 이 시간 동안 JavaScript가 멈춰있으면 버튼 클릭도, 스크롤도, 아무것도 작동하지 않는다. 비동기는 '기다리는 동안 다른 일을 해라'는 방식이다." },
      { type: "h2", text: "Promise: '나중에 결과를 줄게'라는 약속" },
      { type: "p", text: "Promise는 지금 당장 결과가 없지만, 언젠가 성공(resolve) 또는 실패(reject)할 작업을 표현한다. .then()으로 성공 결과를, .catch()로 실패를 처리한다." },
      { type: "code", lang: "javascript", text: "// Promise 사용 예시\nfetch('https://api.example.com/user/1')\n  .then(response => response.json())   // 응답을 JSON으로 변환\n  .then(user => {\n    console.log(user.name)             // 데이터 사용\n  })\n  .catch(error => {\n    console.error('에러 발생:', error)  // 실패 처리\n  })\n\n// 직접 Promise 만들기\nfunction delay(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms))\n}\n\ndelay(1000).then(() => console.log('1초 후 실행'))" },
      { type: "h2", text: "async/await: Promise를 동기 코드처럼 쓰기" },
      { type: "p", text: "Promise의 .then() 체인이 길어지면 가독성이 떨어진다. async/await는 같은 동작을 더 읽기 쉽게 만들어준다. async 함수 안에서 await를 쓰면 Promise가 완료될 때까지 기다린다." },
      { type: "code", lang: "javascript", text: "// Promise 체인 방식\nfunction getUserPosts() {\n  return fetch('/api/user')\n    .then(res => res.json())\n    .then(user => fetch(`/api/posts?userId=${user.id}`))\n    .then(res => res.json())\n    .catch(error => console.error(error))\n}\n\n// async/await 방식 (같은 동작, 더 읽기 쉬움)\nasync function getUserPosts() {\n  try {\n    const userRes = await fetch('/api/user')\n    const user = await userRes.json()\n\n    const postsRes = await fetch(`/api/posts?userId=${user.id}`)\n    const posts = await postsRes.json()\n\n    return posts\n  } catch (error) {\n    console.error('에러 발생:', error)\n  }\n}" },
      { type: "h2", text: "병렬 실행: Promise.all" },
      { type: "p", text: "두 API를 순서대로 호출할 필요가 없다면 Promise.all로 동시에 실행하면 훨씬 빠르다. 첫 번째가 끝날 때까지 두 번째가 기다릴 필요가 없기 때문이다." },
      { type: "code", lang: "javascript", text: "// 순서대로: 합계 시간 = A + B\nconst user = await fetchUser()    // 300ms\nconst posts = await fetchPosts()  // 200ms → 총 500ms\n\n// 병렬: 합계 시간 = max(A, B)\nconst [user, posts] = await Promise.all([\n  fetchUser(),   // 300ms\n  fetchPosts(),  // 200ms\n])  // → 총 300ms" },
      { type: "quote", text: "async/await는 비동기 코드를 없애는 게 아니라, 동기 코드처럼 읽힐 수 있게 감싸는 문법이다. 내부는 여전히 Promise다." },
    ]
  },
  {
    id: "css-flexbox-vs-grid",
    title: "CSS Flexbox vs Grid - 언제 뭘 쓸까",
    subtitle: "두 레이아웃 시스템의 차이, 예제로 한 번에 이해한다",
    date: "2026-06-16",
    readMin: 6,
    tags: ["CSS", "레이아웃"],
    category: "Frontend",
    excerpt: "Flexbox와 Grid 둘 다 배웠는데, 실제로 코드를 짤 때 뭘 써야 할지 매번 고민했다. '1차원이면 Flex, 2차원이면 Grid'라는 말이 처음엔 와닿지 않았다.",
    body: [
      { type: "p", text: "Flexbox와 Grid는 둘 다 레이아웃 도구다. 하지만 '생각하는 방향'이 다르다. Flexbox는 아이템이 흐르는 방향을 기준으로, Grid는 공간을 먼저 정의하고 아이템을 배치한다." },
      { type: "h2", text: "Flexbox: 아이템의 흐름을 제어할 때" },
      { type: "p", text: "Flexbox는 한 방향(가로 또는 세로)으로 아이템을 나열할 때 강력하다. 내비게이션 바, 버튼 그룹, 카드 한 줄처럼 '아이템들을 일렬로 정렬'하는 상황에 딱 맞다." },
      { type: "code", lang: "css", text: "/* 내비게이션 바: 가로로 아이템 정렬 */\n.navbar {\n  display: flex;\n  justify-content: space-between;  /* 좌우 끝으로 */\n  align-items: center;             /* 세로 중앙 */\n  padding: 0 24px;\n}\n\n/* 버튼 그룹: 오른쪽 정렬 */\n.button-group {\n  display: flex;\n  gap: 8px;\n  justify-content: flex-end;\n}" },
      { type: "h2", text: "Grid: 레이아웃 전체를 설계할 때" },
      { type: "p", text: "Grid는 행과 열을 동시에 제어한다. 전체 페이지 레이아웃, 카드 갤러리, 대시보드처럼 '2차원 공간에 아이템을 배치'하는 상황에 쓴다." },
      { type: "code", lang: "css", text: "/* 카드 갤러리: 반응형으로 열 자동 조정 */\n.card-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\n  gap: 24px;\n}\n\n/* 전체 페이지 레이아웃 */\n.page-layout {\n  display: grid;\n  grid-template-areas:\n    'header header'\n    'sidebar main'\n    'footer footer';\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: 60px 1fr 40px;\n  min-height: 100vh;\n}\n\n.header { grid-area: header; }\n.sidebar { grid-area: sidebar; }\n.main { grid-area: main; }" },
      { type: "h2", text: "언제 어떤 걸 써야 하나" },
      { type: "p", text: "규칙은 단순하다. 한 방향(가로 또는 세로)으로만 나열하면 Flexbox, 행과 열 모두를 제어해야 하면 Grid다. 그리고 둘을 함께 쓰는 게 대부분의 실제 레이아웃이다. Grid로 전체 구조를 잡고, 각 영역 안에서 Flexbox로 정렬하는 패턴이 가장 흔하다." },
      { type: "quote", text: "Flexbox는 콘텐츠가 레이아웃을 결정한다. Grid는 레이아웃이 콘텐츠를 담는다. 이 차이를 이해하면 어떤 걸 써야 할지 자연스럽게 보인다." },
    ]
  },
  {
    id: "git-basics-for-beginners",
    title: "Git 초보자 가이드 - commit, push, pull의 의미",
    subtitle: "버전 관리가 왜 필요한지부터, 실제 워크플로우까지",
    date: "2026-06-16",
    readMin: 6,
    tags: ["Git", "개발 팁"],
    category: "Tools",
    excerpt: "처음 Git을 배울 때 명령어는 외웠는데 왜 하는지 몰랐다. commit이 저장이고, push가 업로드라는 걸 알면서도 실수를 반복했다.",
    body: [
      { type: "p", text: "Git은 코드의 '역사'를 기록하는 도구다. 언제, 누가, 무엇을 바꿨는지 모든 변경사항을 저장한다. 실수해도 예전 버전으로 되돌릴 수 있고, 여러 명이 동시에 작업해도 충돌을 관리할 수 있다." },
      { type: "h2", text: "핵심 개념 3가지" },
      { type: "p", text: "Working Directory(작업 공간): 지금 편집 중인 파일들. Staging Area(스테이지): 커밋할 파일을 선택해 올려두는 임시 공간. Repository(저장소): 커밋된 변경 이력이 모두 저장되는 곳." },
      { type: "code", lang: "bash", text: "# 기본 워크플로우\ngit status              # 현재 변경사항 확인\ngit add index.html      # 스테이지에 파일 올리기\ngit add .               # 모든 변경 파일 스테이지에 올리기\ngit commit -m \"로그인 폼 추가\"  # 스냅샷 저장 (로컬)\ngit push origin main    # GitHub에 업로드\ngit pull origin main    # GitHub에서 최신 버전 받아오기" },
      { type: "h2", text: "브랜치: 실험을 안전하게 하는 방법" },
      { type: "p", text: "브랜치는 메인 코드에서 분기한 '사본'이다. 새 기능을 브랜치에서 개발하고, 완성되면 메인에 합친다(merge). 실수해도 메인 코드는 안전하다." },
      { type: "code", lang: "bash", text: "git checkout -b feature/login  # 새 브랜치 만들고 이동\n# ... 작업 ...\ngit add .\ngit commit -m \"로그인 기능 구현\"\ngit checkout main              # 메인으로 돌아오기\ngit merge feature/login        # 브랜치 합치기" },
      { type: "h2", text: "자주 하는 실수와 해결법" },
      { type: "p", text: "가장 흔한 실수 두 가지. 첫째, 커밋 메시지를 '수정', 'fix' 처럼 모호하게 쓰는 것. 나중에 역사를 봤을 때 무슨 변경인지 알 수 없다. '로그인 버튼 색상 파란색으로 변경'처럼 구체적으로 써야 한다. 둘째, push하기 전에 pull을 안 해서 충돌 나는 것. 항상 pull 먼저, push 나중이다." },
      { type: "code", lang: "bash", text: "# 좋은 커밋 메시지 예시\ngit commit -m \"feat: 소셜 로그인(Google) 추가\"\ngit commit -m \"fix: 모바일에서 버튼 클릭 안 되는 버그 수정\"\ngit commit -m \"docs: README 설치 방법 업데이트\"\n\n# 충돌 방지 루틴\ngit pull origin main   # 먼저 받아오고\n# 충돌 해결 후\ngit push origin main   # 그 다음 올리기" },
      { type: "quote", text: "Git을 처음 쓸 때 가장 중요한 습관은 '자주, 작게 커밋하기'다. 하루치 작업을 한 번에 커밋하면 무엇을 바꿨는지 추적하기 어렵다." },
    ]
  },
  {
    id: "rest-vs-graphql-api-design",
    title: "API 설계의 기초 - REST vs GraphQL",
    subtitle: "어떻게 다르고, 무엇을 언제 써야 하는가",
    date: "2026-06-16",
    readMin: 7,
    tags: ["Backend", "API"],
    category: "Backend",
    excerpt: "회사에서 GraphQL 프로젝트에 투입됐을 때, REST만 알던 나는 왜 이렇게 복잡하게 쓰나 싶었다. 6개월 후엔 생각이 달라졌다.",
    body: [
      { type: "p", text: "API는 클라이언트(앱, 브라우저)와 서버가 데이터를 주고받는 방식이다. REST와 GraphQL은 둘 다 HTTP를 쓰지만, 데이터를 요청하고 응답하는 방식이 근본적으로 다르다." },
      { type: "h2", text: "REST: URL이 리소스를 표현한다" },
      { type: "p", text: "REST는 엔드포인트(URL) 하나가 리소스 하나를 나타낸다. /users는 사용자 목록, /users/1은 특정 사용자, /users/1/posts는 그 사용자의 글 목록. HTTP 메서드(GET, POST, PUT, DELETE)가 동작을 표현한다." },
      { type: "code", lang: "bash", text: "# REST API 예시\nGET    /users          # 사용자 목록\nGET    /users/1        # 특정 사용자\nPOST   /users          # 사용자 생성\nPUT    /users/1        # 사용자 수정\nDELETE /users/1        # 사용자 삭제\n\nGET    /users/1/posts  # 사용자 1의 글 목록" },
      { type: "h2", text: "GraphQL: 필요한 데이터를 정확히 요청한다" },
      { type: "p", text: "GraphQL은 엔드포인트가 하나다(/graphql). 대신 쿼리 언어로 원하는 데이터의 형태를 클라이언트가 직접 명시한다. 필요한 필드만 받아올 수 있고, 여러 리소스를 한 번의 요청으로 가져올 수 있다." },
      { type: "code", lang: "graphql", text: "# GraphQL 쿼리: 사용자와 그 사람의 글 제목을 한 번에\nquery {\n  user(id: \"1\") {\n    name\n    email\n    posts {\n      title\n      createdAt\n    }\n  }\n}\n\n# 응답도 쿼리 모양 그대로\n{\n  \"user\": {\n    \"name\": \"켈빈\",\n    \"email\": \"kelvin@example.com\",\n    \"posts\": [\n      { \"title\": \"첫 번째 글\", \"createdAt\": \"2026-06-01\" }\n    ]\n  }\n}" },
      { type: "h2", text: "REST의 Over-fetching 문제" },
      { type: "p", text: "사용자 이름만 필요한데 REST는 사용자 전체 데이터를 준다. 이걸 Over-fetching이라 한다. 반대로 여러 리소스가 필요할 때 요청을 여러 번 보내야 하는 건 Under-fetching이다. GraphQL은 둘 다 해결한다." },
      { type: "h2", text: "언제 뭘 쓸까" },
      { type: "p", text: "REST가 나은 경우: 단순한 CRUD 앱, 팀이 REST에 익숙할 때, 캐싱이 중요할 때(HTTP 캐시 활용). GraphQL이 나은 경우: 모바일 앱처럼 네트워크 비용이 중요할 때, 클라이언트마다 필요한 데이터가 다를 때, 복잡하게 연결된 데이터를 다룰 때." },
      { type: "quote", text: "REST와 GraphQL은 경쟁이 아니라 트레이드오프다. 단순함이 우선이면 REST, 유연성이 우선이면 GraphQL. 둘 다 좋은 도구다." },
    ]
  },
  {
    id: "react-performance-optimization",
    title: "성능 최적화 첫 발 - 렌더링 성능 개선하기",
    subtitle: "React.memo, useMemo, lazy loading — 언제 왜 쓰는지",
    date: "2026-06-16",
    readMin: 7,
    tags: ["Performance", "React"],
    category: "Frontend",
    excerpt: "버튼 하나 클릭했는데 전체 페이지가 다시 그려진다. React를 처음 쓸 때 흔히 만나는 상황이다. 최적화 도구를 쓰기 전에 '왜 느린지'를 아는 게 먼저다.",
    body: [
      { type: "p", text: "React는 상태(state)가 바뀌면 해당 컴포넌트와 모든 자식 컴포넌트를 리렌더링한다. 이게 기본 동작이다. 자식이 많거나, 렌더링이 비싸면 성능 문제가 생긴다." },
      { type: "h2", text: "React.memo: 같은 props면 리렌더링 건너뛰기" },
      { type: "p", text: "React.memo는 컴포넌트를 감싸서, 이전 props와 동일하면 리렌더링하지 않는다. 부모가 자주 리렌더링되는데 자식은 props가 바뀌지 않을 때 효과적이다." },
      { type: "code", lang: "typescript", text: "// memo 없이: 부모 리렌더링 → 자식도 리렌더링\nfunction ExpensiveList({ items }: { items: Item[] }) {\n  // items가 안 바뀌어도 매번 다시 그림\n  return <ul>{items.map(item => <li key={item.id}>{item.name}</li>)}</ul>\n}\n\n// memo 적용: props가 같으면 리렌더링 건너뜀\nconst ExpensiveList = React.memo(function({ items }: { items: Item[] }) {\n  return <ul>{items.map(item => <li key={item.id}>{item.name}</li>)}</ul>\n})" },
      { type: "h2", text: "useMemo: 비싼 계산 결과 캐시하기" },
      { type: "p", text: "렌더링마다 무거운 계산을 반복하는 게 문제라면 useMemo를 쓴다. 의존성 값이 바뀔 때만 다시 계산하고, 그 전까지는 이전 결과를 그대로 쓴다." },
      { type: "code", lang: "typescript", text: "// 리렌더링마다 10만 개를 다시 필터링\nfunction ProductList({ products, query }) {\n  const filtered = products.filter(p =>\n    p.name.includes(query)  // 매 렌더마다 실행\n  )\n\n  return <ul>{filtered.map(p => <li>{p.name}</li>)}</ul>\n}\n\n// useMemo: query나 products가 바뀔 때만 필터링\nfunction ProductList({ products, query }) {\n  const filtered = useMemo(\n    () => products.filter(p => p.name.includes(query)),\n    [products, query]  // 이 값이 바뀔 때만 재계산\n  )\n\n  return <ul>{filtered.map(p => <li>{p.name}</li>)}</ul>\n}" },
      { type: "h2", text: "lazy loading: 필요할 때 코드 불러오기" },
      { type: "p", text: "페이지에 진입할 때 모든 컴포넌트 코드를 한 번에 불러오면 초기 로딩이 느리다. React.lazy와 Suspense를 쓰면 특정 컴포넌트를 필요할 때 불러올 수 있다." },
      { type: "code", lang: "typescript", text: "import { lazy, Suspense } from 'react'\n\n// 이 컴포넌트의 코드는 실제로 렌더링될 때 불러옴\nconst HeavyChart = lazy(() => import('./HeavyChart'))\n\nfunction Dashboard() {\n  return (\n    <div>\n      <Suspense fallback={<p>차트 로딩 중...</p>}>\n        <HeavyChart />  {/* 처음 렌더링 시 코드 다운로드 */}\n      </Suspense>\n    </div>\n  )\n}" },
      { type: "quote", text: "최적화는 문제가 생겼을 때 하는 것이다. 먼저 만들고, 느리다고 느껴지면 측정하고, 그 다음 최적화한다. 아직 느리지도 않은 코드를 최적화하는 건 시간 낭비다." },
    ]
  },
  {
    id: "testing-automation-for-beginners",
    title: "배포 후 버그를 줄이려면 - 테스트 자동화 입문",
    subtitle: "단위 테스트, 통합 테스트, TDD — 무엇부터 시작할까",
    date: "2026-06-16",
    readMin: 6,
    tags: ["Testing", "개발 팁"],
    category: "Tools",
    excerpt: "테스트 코드를 작성하면 개발이 느려진다고 생각했다. 버그를 세 번째 직접 고친 후에야 테스트가 오히려 빠르게 해준다는 걸 알았다.",
    body: [
      { type: "p", text: "테스트 코드는 '코드를 검사하는 코드'다. 새 기능을 추가하거나 코드를 수정했을 때, 기존 기능이 여전히 잘 동작하는지 자동으로 확인해준다." },
      { type: "h2", text: "왜 테스트가 필요한가" },
      { type: "p", text: "수동으로 테스트하는 건 개발할수록 느려진다. 기능이 10개면 10가지를 클릭해봐야 하고, 50개면 50가지다. 자동화 테스트는 수백 가지 시나리오를 1초 안에 실행한다. 배포 전에 버그를 잡는 건 배포 후에 잡는 것보다 10배 빠르다." },
      { type: "h2", text: "단위 테스트: 함수 하나씩 검증하기" },
      { type: "p", text: "가장 기본적인 테스트다. 함수에 입력을 주고 기대한 출력이 나오는지 확인한다. JavaScript에선 Jest나 Vitest를 주로 쓴다." },
      { type: "code", lang: "typescript", text: "// 테스트할 함수\nfunction formatPrice(price: number, currency: string): string {\n  return `${price.toLocaleString()}${currency}`\n}\n\n// 단위 테스트 (Vitest)\nimport { describe, it, expect } from 'vitest'\n\ndescribe('formatPrice', () => {\n  it('숫자에 천 단위 콤마를 추가한다', () => {\n    expect(formatPrice(1000, '원')).toBe('1,000원')\n  })\n\n  it('큰 숫자도 올바르게 포맷한다', () => {\n    expect(formatPrice(1234567, '원')).toBe('1,234,567원')\n  })\n\n  it('0도 처리한다', () => {\n    expect(formatPrice(0, '원')).toBe('0원')\n  })\n})" },
      { type: "h2", text: "통합 테스트: 여러 부분이 함께 동작하는지 확인" },
      { type: "p", text: "단위 테스트는 함수 하나만 본다. 통합 테스트는 컴포넌트나 모듈이 실제로 상호작용하는 방식을 테스트한다. React Testing Library가 대표적이다." },
      { type: "code", lang: "typescript", text: "import { render, screen, fireEvent } from '@testing-library/react'\nimport LoginForm from './LoginForm'\n\ntest('로그인 버튼 클릭 시 이메일과 비밀번호를 제출한다', async () => {\n  const handleSubmit = vi.fn()\n  render(<LoginForm onSubmit={handleSubmit} />)\n\n  // 폼 채우기\n  fireEvent.change(screen.getByLabelText('이메일'), {\n    target: { value: 'test@example.com' }\n  })\n  fireEvent.change(screen.getByLabelText('비밀번호'), {\n    target: { value: 'password123' }\n  })\n\n  // 제출\n  fireEvent.click(screen.getByText('로그인'))\n\n  // 검증\n  expect(handleSubmit).toHaveBeenCalledWith({\n    email: 'test@example.com',\n    password: 'password123'\n  })\n})" },
      { type: "h2", text: "처음 시작한다면" },
      { type: "p", text: "처음부터 모든 코드에 테스트를 붙이려 하면 지친다. 먼저 '계산 로직이 있는 유틸 함수'부터 시작하자. 입출력이 명확해서 테스트 작성이 쉽고, 효과도 바로 느껴진다." },
      { type: "quote", text: "테스트를 작성하는 건 미래의 나에게 보내는 편지다. 3개월 후 코드를 수정할 때, 테스트가 있으면 무엇을 조심해야 하는지 알 수 있다." },
    ]
  },
  {
    id: "sql-vs-nosql-database-basics",
    title: "데이터베이스 기초 - SQL vs NoSQL",
    subtitle: "어떤 데이터베이스를 골라야 하는지, 기준을 잡아보자",
    date: "2026-06-16",
    readMin: 7,
    tags: ["Database", "Backend"],
    category: "Backend",
    excerpt: "처음 프로젝트를 시작할 때 MySQL이냐 MongoDB냐를 고민했다. 돌이켜보면 차이를 제대로 모른 채로 선택했다. 이 글은 그 기준을 잡아준다.",
    body: [
      { type: "p", text: "데이터베이스는 데이터를 저장하고 조회하는 시스템이다. SQL 데이터베이스(MySQL, PostgreSQL)는 표 형태로, NoSQL 데이터베이스(MongoDB, Redis)는 다양한 형태로 저장한다. 어느 쪽이 낫다는 게 아니라, 상황에 맞는 도구가 다르다." },
      { type: "h2", text: "SQL: 표 형태로 데이터를 관리한다" },
      { type: "p", text: "SQL 데이터베이스는 행과 열로 이루어진 표(테이블)에 데이터를 저장한다. 각 행은 하나의 레코드, 각 열은 속성이다. 여러 테이블을 연결(JOIN)해서 복잡한 데이터를 표현한다." },
      { type: "code", lang: "sql", text: "-- 사용자 테이블\nCREATE TABLE users (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  name VARCHAR(100) NOT NULL,\n  email VARCHAR(100) UNIQUE NOT NULL,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- 게시글 테이블 (사용자와 연결)\nCREATE TABLE posts (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  user_id INT,\n  title VARCHAR(200) NOT NULL,\n  content TEXT,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);\n\n-- 사용자와 글을 연결해서 조회\nSELECT users.name, posts.title\nFROM users\nJOIN posts ON users.id = posts.user_id\nWHERE users.id = 1;" },
      { type: "h2", text: "NoSQL: 유연한 구조로 빠르게 저장한다" },
      { type: "p", text: "MongoDB 같은 NoSQL은 JSON 형태의 문서(document)로 저장한다. 스키마가 유연해서 각 문서가 다른 구조를 가져도 된다. 복잡한 JOIN 없이 관련 데이터를 한 문서에 넣을 수 있다." },
      { type: "code", lang: "javascript", text: "// MongoDB 문서 예시: 사용자 정보를 하나의 문서에\n{\n  _id: ObjectId('..'),\n  name: '켈빈',\n  email: 'kelvin@example.com',\n  posts: [\n    { title: '첫 글', createdAt: '2026-06-01' },\n    { title: '두 번째 글', createdAt: '2026-06-10' }\n  ],\n  preferences: {\n    darkMode: true,\n    language: 'ko'\n  }\n}\n\n// 조회 예시\ndb.users.find({ name: '켈빈' })\ndb.users.findOne({ _id: userId })" },
      { type: "h2", text: "무엇을 골라야 할까" },
      { type: "p", text: "SQL이 나은 경우: 데이터 간 관계가 복잡할 때(주문-상품-사용자), 데이터 정합성이 중요할 때(금융, 의료), 복잡한 쿼리가 필요할 때. NoSQL이 나은 경우: 빠르게 프로토타입을 만들 때, 데이터 구조가 자주 바뀔 때, 대용량 데이터를 빠르게 읽고 쓸 때." },
      { type: "quote", text: "사실 대부분의 서비스는 PostgreSQL 하나로 충분하다. NoSQL이 필요한 규모와 상황이 되면 그때 전환해도 늦지 않다. 처음부터 과하게 설계하지 말자." },
    ]
  },
  {
    id: "ai-tools-for-developers",
    title: "AI와 개발자 - ChatGPT를 개발에 활용하는 방법",
    subtitle: "코드 생성기로 쓰면 실패한다. 이렇게 써야 한다",
    date: "2026-06-16",
    readMin: 6,
    tags: ["AI", "개발 팁", "Claude Code"],
    category: "Tools",
    excerpt: "AI가 코드를 짜주니까 개발자가 필요 없다는 말이 있다. 직접 써보니 반은 맞고 반은 틀렸다. AI를 제대로 쓰는 법과 함정을 정리한다.",
    body: [
      { type: "p", text: "ChatGPT, Claude, GitHub Copilot 같은 AI 도구는 이제 개발자의 기본 장비가 됐다. 그런데 '코드 생성기'로만 쓰면 실력이 늘지 않고, 버그를 못 잡는 코드를 복붙하게 된다." },
      { type: "h2", text: "잘못된 사용법: 코드를 그냥 받아서 붙여넣기" },
      { type: "p", text: "AI가 만들어 준 코드는 겉보기엔 완벽해 보인다. 그런데 에러 처리가 빠져있거나, 최신 라이브러리 API와 다르거나, 프로젝트 맥락을 모르고 짠 경우가 많다. 이해 없이 붙여넣으면 나중에 디버깅을 못 한다." },
      { type: "h2", text: "올바른 사용법 4가지" },
      { type: "p", text: "첫째, 에러 메시지 디버깅. 스택 트레이스 전체를 붙여넣고 '이 에러의 원인을 설명해줘'라고 하면 구글링 10분을 2분으로 줄여준다. 둘째, 개념 이해. '비동기 처리가 뭔지 실생활 예시로 설명해줘'처럼 개념을 먼저 이해하는 데 쓴다." },
      { type: "code", lang: "typescript", text: "// 나쁜 요청: 코드만 받는다\n\"useEffect로 API 호출하는 컴포넌트 만들어줘\"\n\n// 좋은 요청: 이해를 강제한다\n\"아래 코드에서 왜 무한 렌더링이 발생하는지 설명해줘.\n그리고 어떻게 고치면 좋을지 알려줘.\n\nuseEffect(() => {\n  setData(fetch('/api/data'))\n})" },
      { type: "h2", text: "AI가 틀리는 경우" },
      { type: "p", text: "AI는 자신 있게 틀린다. 특히 최신 라이브러리 버전(Next.js 15, React 19 등)에서 존재하지 않는 API를 만들어내기도 한다. 생성된 코드는 반드시 공식 문서와 대조하고, 직접 실행해서 확인해야 한다." },
      { type: "h2", text: "AI와 함께 배우는 방법" },
      { type: "p", text: "AI를 가장 잘 활용하는 방법은 '선생님'으로 쓰는 것이다. 코드를 받기 전에 '왜 이렇게 해야 하는지' 먼저 물어본다. 이해한 다음 코드를 보면 내 것이 된다. 이해 없이 코드만 받으면 영원히 AI에 의존하게 된다." },
      { type: "quote", text: "AI는 생각을 대신해주는 게 아니라 생각의 속도를 높여주는 도구다. 생각 자체를 AI에게 넘기면 내 실력은 멈춘다." },
    ]
  },
  {
    id: "web-security-basics",
    title: "보안 기초 - 웹 개발자가 알아야 할 5가지",
    subtitle: "XSS, CSRF, 비밀번호 해싱, API 키 관리, HTTPS",
    date: "2026-06-16",
    readMin: 8,
    tags: ["Security", "개발 팁"],
    category: "Backend",
    excerpt: "보안을 나중에 생각하면 나중에 큰일 난다. 시작부터 알아야 할 기초 5가지를 코드 예시와 함께 정리했다.",
    body: [
      { type: "p", text: "보안 문제는 개발 막바지에 '나중에 추가하자'는 생각으로 미루다 배포 후 사고로 이어진다. 처음부터 기초만 알아도 대부분의 일반적인 공격을 막을 수 있다." },
      { type: "h2", text: "1. XSS (Cross-Site Scripting)" },
      { type: "p", text: "사용자 입력을 그대로 HTML에 삽입하면 공격자가 악의적인 스크립트를 심을 수 있다. 댓글에 <script>alert('해킹')</script>를 입력하면 그게 실행되는 것이다." },
      { type: "code", lang: "typescript", text: "// 위험: 사용자 입력을 innerHTML에 직접 삽입\ndiv.innerHTML = userInput  // XSS 취약점\n\n// 안전: textContent 사용 (스크립트 실행 안 됨)\ndiv.textContent = userInput\n\n// React는 기본적으로 이스케이프 처리\nfunction Comment({ text }) {\n  return <p>{text}</p>  // 안전: 자동으로 이스케이프\n}\n\n// dangerouslySetInnerHTML은 정말 필요할 때만\nfunction Comment({ text }) {\n  // 이름에 'dangerous'가 들어간 이유가 있다\n  return <p dangerouslySetInnerHTML={{ __html: text }} />\n}" },
      { type: "h2", text: "2. 비밀번호는 절대 평문으로 저장하지 않는다" },
      { type: "p", text: "데이터베이스가 유출됐을 때 비밀번호가 그대로면 모든 사용자 계정이 노출된다. bcrypt 같은 해시 함수로 변환해서 저장해야 한다. 해시는 복원이 불가능하다." },
      { type: "code", lang: "typescript", text: "import bcrypt from 'bcrypt'\n\n// 회원가입: 비밀번호 해싱 후 저장\nasync function register(email: string, password: string) {\n  const saltRounds = 12  // 높을수록 안전하지만 느림\n  const hashedPassword = await bcrypt.hash(password, saltRounds)\n  await db.users.create({ email, password: hashedPassword })\n}\n\n// 로그인: 해시 비교\nasync function login(email: string, password: string) {\n  const user = await db.users.findOne({ email })\n  if (!user) return false\n\n  const isMatch = await bcrypt.compare(password, user.password)\n  return isMatch\n}" },
      { type: "h2", text: "3. API 키는 절대 코드에 넣지 않는다" },
      { type: "p", text: "GitHub에 API 키를 올리면 수 분 안에 크롤러가 감지하고 악용한다. 환경 변수(.env)에 저장하고, .gitignore에 .env를 추가해서 절대 커밋하지 않아야 한다." },
      { type: "code", lang: "bash", text: "# .env 파일 (절대 커밋하지 않는다)\nOPENAI_API_KEY=sk-...\nDATABASE_URL=postgresql://...\n\n# .gitignore에 반드시 추가\n.env\n.env.local\n.env.production" },
      { type: "h2", text: "4. HTTPS는 선택이 아니다" },
      { type: "p", text: "HTTP는 데이터가 암호화 없이 전송된다. 같은 네트워크(카페 와이파이 등)에서 패킷을 가로채면 로그인 정보가 그대로 보인다. HTTPS는 모든 통신을 암호화한다. Vercel, Netlify 같은 플랫폼은 기본으로 HTTPS를 제공한다." },
      { type: "h2", text: "5. 입력 값은 항상 검증한다" },
      { type: "p", text: "클라이언트에서 검증해도 서버에서 다시 검증해야 한다. 클라이언트 검증은 사용자 편의를 위한 것이고, 서버 검증이 실제 보안이다. Zod 같은 라이브러리로 서버에서 입력 스키마를 검증하자." },
      { type: "quote", text: "보안의 첫 번째 원칙은 '사용자 입력을 믿지 않는 것'이다. 모든 입력은 잠재적인 공격으로 가정하고 검증해야 한다." },
    ]
  },
];

export function getPosts() {
  return POSTS;
}

export function getPostById(id: string) {
  return POSTS.find(p => p.id === id);
}
